import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import UserLayout from "@/layout/UserLayout";

export default function Home() {
  const router = useRouter();
  return (
    <UserLayout>
      <Head>
        <title>Nexa | Connect. Share. Grow.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="\logo.png" />
      </Head>
      <div className={styles.container}>
        <div className={styles.mainContainer}>
          <div className={styles.mainContainerLeft}>
            <h1 className={styles.heading}>
              Build Real <span>Connections</span>, <br /> No Filters, No Fake
              Vibes ✨
            </h1>
            <p className={styles.subheading}>
              A social platform where authenticity matters. <br />
              Share stories, create bonds, and stay true 💙
            </p>

            <div
              className={styles.buttonJoin}
              onClick={() => {
                router.push("/login");
              }}
            >
              <p>🚀 Join Now</p>
            </div>
          </div>
          <div className={styles.mainContainerRight}>
            <img src="/connect.jpg" alt="Connection" />
          </div>
        </div>
      </div>
    </UserLayout>
  );
}
